# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('subtitle', models.CharField(max_length=1000)),
                ('icon', models.FilePathField()),
                ('max_lookahead', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markov.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markov.Sentence')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sentenceorder',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markov.Word'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='words',
            field=models.ManyToManyField(through='markov.SentenceOrder', to='markov.Word'),
        ),
    ]
