# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_word',
            field=models.CharField(default='END', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_word',
            field=models.CharField(default='START', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentenceorder',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_in_sentence', to='markov.Word'),
        ),
    ]
