# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, through='markov.SequenceOrder', to='markov.Word'),
        ),
    ]
