# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markov', '0002_auto_20160130_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
