# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShakespeareSequence',
            fields=[
                ('sequence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markov.Sequence')),
            ],
            bases=('markov.sequence',),
        ),
        migrations.CreateModel(
            name='ShakespeareTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('form', models.CharField(choices=[('SO', 'sonnet'), ('PL', 'play')], default='PL', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='shakespearesequence',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shakespeare.ShakespeareTitle'),
        ),
    ]
